// Step 6 rib-bone loader — atlas variant.
//
// Pre-atlas this module fanned out 26 separate fetches to /models/bones/rib/
// Rib (1..26).glb (~2 MB each, raw). Now reads ONE Draco-compressed
// /models/bones/rib-atlas.glb (~150 KB total) generated by
// `npm run build-rib-atlas`.
//
// Returned shape per entry is unchanged: { geometry, position, size }, so
// useRibBoneStep.jsx (and its RIB_BONES position-override table) keeps working
// with no caller changes.

import * as THREE         from 'three'
import { makeGLTFLoader } from '../../../utils/dracoGLTFLoader'

export const TOTAL_RIB_BONES = 26

const ATLAS_PATH = '/models/bones/rib-atlas.glb'
const NODE_PREFIX = 'rib_'   // matches build-bone-atlas.mjs naming: rib_001 .. rib_026

const _loader = makeGLTFLoader()

// Lambert + warm emissive, matches the visual palette of the other bone steps.
export const BONE_MATERIAL = new THREE.MeshLambertMaterial({
  color:             '#fff4cf',
  emissive:          new THREE.Color('#ffce4d'),
  emissiveIntensity: 1.4,
})

// Read one atlas, return a sparse Array<BoneEntry|null> indexed by 1-based
// piece number (slot 0 = bone 1, slot 25 = bone 26). Missing slots stay null.
function loadAtlas() {
  return new Promise((resolve, reject) => {
    _loader.load(
      ATLAS_PATH,
      (gltf) => {
        const out = new Array(TOTAL_RIB_BONES).fill(null)
        gltf.scene.updateMatrixWorld(true)
        gltf.scene.traverse((node) => {
          if (!node.isMesh) return
          const m = node.name.match(new RegExp(`^${NODE_PREFIX}(\\d+)$`))
          if (!m) return
          const idx = parseInt(m[1], 10) - 1
          if (idx < 0 || idx >= TOTAL_RIB_BONES) return

          // Bake the atlas node's world transform into the geometry so each
          // entry behaves like the old per-piece loader did (atlas-baked
          // positions are already correct because the build script flattened
          // them; this matrix is identity in normal cases but kept for safety).
          const geometry = node.geometry.clone()
          geometry.applyMatrix4(node.matrixWorld)

          const box      = new THREE.Box3().setFromBufferAttribute(geometry.attributes.position)
          const position = box.getCenter(new THREE.Vector3())
          const size     = box.getSize(new THREE.Vector3())
          // Center the geometry on origin so the position vector drives placement.
          geometry.translate(-position.x, -position.y, -position.z)

          out[idx] = { geometry, position, size }
        })
        resolve(out)
      },
      undefined,
      reject,
    )
  })
}

let _cachePromise = null

// Lazy: cache primes on first call. Step 6 calls this from useRibBoneStep.jsx
// inside useEffect, so the atlas + decoder cost is paid at step entry rather
// than at sim mount. Earlier steps may opportunistically call this from their
// own useEffect to pre-warm one step ahead.
export function loadRibBones() {
  if (_cachePromise) return _cachePromise
  _cachePromise = loadAtlas().catch((err) => {
    console.error('[ribBonesLoader] atlas load failed:', err)
    return new Array(TOTAL_RIB_BONES).fill(null)
  })
  return _cachePromise
}
