// Step 9 lateral-spine loader — atlas variant.
//
// Pre-atlas this module fanned out 42 separate fetches to
//   /models/bones/Laterals/Lateral (1..42).glb  (~33 MB raw total)
// Now reads ONE Draco-compressed /models/bones/lateral-atlas.glb
// (~140 KB total) generated by `npm run build-lateral-atlas`.
//
// Returned shape per entry is unchanged: { geometry, position, size }, so
// useLateralBonesStep.jsx (and its LATERAL_BONES position-override table)
// keeps working with no caller changes.
//
// The autoScatter step seeds positions for entries that don't have a manual
// override yet — kept so __dumpLateralBones() devtools helper continues to
// produce a sensible starter table during visual tuning.

import * as THREE         from 'three'
import { makeGLTFLoader } from '../../../utils/dracoGLTFLoader'

export const TOTAL_LATERAL_BONES = 42

const ATLAS_PATH  = '/models/bones/lateral-atlas.glb'
const NODE_PREFIX = 'lateral_'   // matches build-bone-atlas.mjs: lateral_001 .. lateral_042

// Shared Lambert material (per-vertex lighting — cheap on integrated GPUs;
// matches the palette used by Step 6 / 7 / 8 bone clusters).
export const BONE_MATERIAL = new THREE.MeshLambertMaterial({
  color:             '#fff4cf',
  emissive:          new THREE.Color('#ffce4d'),
  emissiveIntensity: 1.4,
})

const _loader = makeGLTFLoader()

// Auto-scatter geometry: two bilateral rows of 21 bones, head→tail along z.
// LATERAL_BONES in useLateralBonesStep.jsx normally overrides every entry; this
// only matters when a position-table slot is null (e.g. during visual tuning).
const Z_MIN    = -1.05
const Z_MAX    =  1.05
const X_OFFSET =  0.18
const Y_BASE   =  0.50
const PER_ROW  = TOTAL_LATERAL_BONES / 2   // 21 per side

function autoScatterBones(bones) {
  for (let i = 0; i < bones.length; i++) {
    const b = bones[i]
    if (!b) continue
    const side  = i < PER_ROW ? -1 : 1
    const inRow = i < PER_ROW ? i  : i - PER_ROW
    const t     = (inRow + 0.5) / PER_ROW
    const z     = THREE.MathUtils.lerp(Z_MIN, Z_MAX, t)
    const y     = Y_BASE + Math.sin(t * Math.PI) * 0.04
    b.position  = new THREE.Vector3(side * X_OFFSET, y, z)
  }
}

// Read the atlas, return a sparse Array<BoneEntry|null> indexed 0..41.
function loadAtlas() {
  return new Promise((resolve, reject) => {
    _loader.load(
      ATLAS_PATH,
      (gltf) => {
        const out = new Array(TOTAL_LATERAL_BONES).fill(null)
        gltf.scene.updateMatrixWorld(true)
        gltf.scene.traverse((node) => {
          if (!node.isMesh) return
          const m = node.name.match(new RegExp(`^${NODE_PREFIX}(\\d+)$`))
          if (!m) return
          const idx = parseInt(m[1], 10) - 1
          if (idx < 0 || idx >= TOTAL_LATERAL_BONES) return

          const geometry = node.geometry.clone()
          geometry.applyMatrix4(node.matrixWorld)

          const box      = new THREE.Box3().setFromBufferAttribute(geometry.attributes.position)
          const position = box.getCenter(new THREE.Vector3())
          const size     = box.getSize(new THREE.Vector3())
          geometry.translate(-position.x, -position.y, -position.z)

          out[idx] = { geometry, position, size }
        })
        resolve(out)
      },
      undefined,
      reject,
    )
  })
}

// DevTools helper — paste __dumpLateralBones() in the browser console to print
// every bone's final auto-scattered [x, y, z] as a copy-pasteable LATERAL_BONES
// config table for manual tuning in useLateralBonesStep.jsx.
function installDumpHelper(promise) {
  if (typeof window === 'undefined') return
  window.__dumpLateralBones = async () => {
    const bones = await promise
    const lines = bones.map((b, i) => {
      if (!b) return `/* ${String(i + 1).padStart(2, ' ')} */ null,`
      const { x, y, z } = b.position
      return `/* ${String(i + 1).padStart(2, ' ')} */ [${x.toFixed(4)}, ${y.toFixed(4)}, ${z.toFixed(4)}],`
    })
    // eslint-disable-next-line no-console
    console.log(lines.join('\n'))
  }
}

let _cachePromise = null

// Returns Promise<Array<BoneEntry|null>> of length 42. Bones whose atlas slot
// was missing remain null; the cluster skips them so a partial atlas is
// non-fatal.
//
// Lazy: cache primes on first call. Step 9 calls this from useLateralBonesStep.jsx
// inside useEffect, so the atlas + decoder cost is paid at step entry rather
// than at sim mount. Earlier steps may opportunistically call this from their
// own useEffect to pre-warm one step ahead.
export function loadLateralBones() {
  if (_cachePromise) return _cachePromise
  _cachePromise = loadAtlas()
    .then((bones) => { autoScatterBones(bones); return bones })
    .catch((err) => {
      console.error('[lateralBonesLoader] atlas load failed:', err)
      return new Array(TOTAL_LATERAL_BONES).fill(null)
    })
  installDumpHelper(_cachePromise)
  return _cachePromise
}
