// Single source of truth for all 11 procedural steps.
// Canonical procedure: Guevara et al. (1973) via Espejo-Hermes (1998) § 4.7.1
// Step 3 scores 0 — it is a navigation mechanic, not a procedural skill.
// The old "Deboning Complete" entry (id:10) is removed — completion is a UI
// screen triggered by isCompleted, not a scored step.

export const STEP_DEFINITIONS = [
  {
    id: 1,
    key: 'trim_fins',
    title: 'Trim Fins',
    shortTitle: 'Trim Fins',
    icon: '🔪',
    description: 'Trim all fins. Remove the fin by making a small cut around the base of each large fin, then pull the fins forward to extract the fin bones and other nuisance bones.',
    instruction: 'Select the knife. Click across each fin base to trim it.',
    completionMessage: 'Fins trimmed — fin bones removed!',
    tool: 'knife',
    requiresHold: false,
    targetCount: 3,
    scoreWeight: 8,
    hints: {
      1: "Take a closer look at the outer shape of the fish — there are parts along the edges that need to be removed first.",
      2: "Select the knife from the toolbox, then click and drag across the base of each fin to trim it. There are 3 fins total.",
    },
  },
  {
    id: 2,
    key: 'washing',
    title: 'Wash the Bangus',
    shortTitle: 'Wash Fish',
    icon: '🚿',
    description: 'Rinse the bangus thoroughly under running water. Remove any slime, residue, or debris from both sides before processing.',
    instruction: 'Move cursor over the fish to wash.',
    completionMessage: 'Fish washed clean!',
    tool: 'water',
    requiresHold: true,
    holdDuration: 3000,
    scoreWeight: 5,
    hints: {
      1: "The fish needs to be cleaned before it can be processed. Check your toolbox — you'll find what you need there.",
      2: "Select the water tool, then slowly move your cursor over the entire surface of the fish. Keep moving — stopping will drain your progress.",
    },
  },
  {
    id: 3,
    key: 'place_on_board',
    title: 'Place on Cutting Board',
    shortTitle: 'Place Fish',
    icon: '🔲',
    description: 'Transfer the clean bangus onto the cutting board, positioning it flat for the dorsal incision.',
    instruction: 'Click and drag the fish to the cutting board.',
    completionMessage: 'Fish placed on board!',
    tool: null,
    requiresHold: false,
    scoreWeight: 0,
  },
  {
    id: 4,
    key: 'dorsal_split',
    title: 'Dorsal Split',
    shortTitle: 'Dorsal Cut',
    icon: '🔪',
    description: 'Split the fish down the dorsal side. Turn the knife flat and extend the cut from the tail to the head along the backbone. Open the fish like a butterfly fillet.',
    instruction: 'Select the knife. Click and drag from the tail to the head along the top of the fish.',
    completionMessage: 'Dorsal split complete — fish opened!',
    tool: 'knife',
    requiresHold: false,
    scoreWeight: 8,
    hints: {
      1: "To open the fish for deboning, you need to make a long cut along its back. Think about the direction and which tool makes clean incisions.",
      2: "Select the knife, then click and drag from the tail end toward the head along the top (dorsal) edge of the fish.",
    },
  },
  {
    id: 5,
    key: 'remove_organs',
    title: 'Remove Gills & Internal Organs',
    shortTitle: 'Remove Organs',
    icon: '🫁',
    description: 'With the fish opened butterfly-style, remove the gills and all internal organs (alimentary canal and associated organs).',
    instruction: 'Select the forceps. Click and drag the highlighted organ region to remove the gills and internal organs.',
    completionMessage: 'Gills and organs removed!',
    tool: 'forceps',
    requiresHold: false,
    scoreWeight: 8,
    hints: {
      1: "Now that the fish is open, there are internal parts that must come out before you can access the bones.",
      2: "Select the forceps, then click and drag the highlighted organ area to pull out the gills and internal organs.",
    },
  },
  {
    id: 6,
    key: 'remove_backbone',
    title: 'Remove Rib Bones',
    shortTitle: 'Remove Rib',
    icon: '🔍',
    description: 'Pull out the rib bones carefully using forceps, starting from the head and working toward the tail to avoid damaging the flesh.',
    instruction: 'Select the forceps. Grab each glowing rib bone and pull it away from the fish.',
    completionMessage: 'Rib bones removed!',
    tool: 'forceps',
    requiresHold: false,
    scoreWeight: 10,
    hints: {
      1: "Inside the open fish, there are bones along the inner cavity that glow to show you where to grab them.",
      2: "Select the forceps, then click each glowing rib bone and drag it away from the fish body to remove it.",
    },
  },
  {
    id: 7,
    key: 'dorsal_bones',
    title: 'Dorsal Bones',
    shortTitle: 'Dorsal Bones',
    icon: '🔍',
    description: 'Make a superficial slit along the dorsal muscle, then carefully pull out the intermuscular dorsal spines from the head toward the tail using forceps.',
    instruction: 'Select the forceps. Grip each highlighted dorsal spine and pull it away from the fish one by one.',
    completionMessage: 'Dorsal spines removed!',
    tool: 'forceps',
    requiresHold: false,
    targetCount: 87,
    scoreWeight: 18,
    hints: {
      1: "There are many small intermuscular spines running through the upper muscle of the fish — they all need to be pulled out individually.",
      2: "Select the forceps, then click each highlighted dorsal spine and drag it away from the fish. Work systematically from one end to the other.",
    },
  },
  {
    id: 8,
    key: 'ventral_bones',
    title: 'Ventral Spines',
    shortTitle: 'Ventral Bones',
    icon: '🔍',
    description: 'Remove the ventral intermuscular spines on the belly side in the same manner as the dorsal spines.',
    instruction: 'Select the forceps. Click each highlighted ventral spine and pull it away.',
    completionMessage: 'Ventral spines removed!',
    tool: 'forceps',
    requiresHold: false,
    targetCount: 48,
    scoreWeight: 15,
    hints: {
      1: "Check the belly side of the fish — there are similar spines there that still need to be removed.",
      2: "Select the forceps, then click each highlighted ventral spine along the belly side and pull it away from the flesh.",
    },
  },
  {
    id: 9,
    key: 'lateral_bones',
    title: 'Y-shaped Lateral Spines',
    shortTitle: 'Lateral Bones',
    icon: '🔍',
    description: 'Extract the filamentous Y-shaped intermuscular spines along the lateral line. These are the hardest bones to locate and are a key learning outcome.',
    instruction: 'Select the forceps. Click each Y-shaped spine along the lateral line and pull it free.',
    completionMessage: 'Lateral Y-spines removed!',
    tool: 'forceps',
    requiresHold: false,
    targetCount: 42,
    scoreWeight: 15,
    hints: {
      1: "There is a line of special Y-shaped bones running along the middle of the fish. These are the smallest and hardest to find.",
      2: "Select the forceps. The Y-shaped spines are highlighted along the lateral line — the midline stripe on the fish. Click each one and drag it free.",
    },
  },
  {
    id: 10,
    key: 'final_rinse',
    title: 'Final Rinse',
    shortTitle: 'Final Rinse',
    icon: '💧',
    description: 'Wash the deboned bangus to remove any remaining bone fragments or debris. The fish is now ready for packing.',
    instruction: 'Carry the fish back to the sink and rinse it under running water.',
    completionMessage: 'Fish rinsed clean — ready for packing!',
    tool: 'water',
    requiresHold: true,
    holdDuration: 2000,
    scoreWeight: 5,
    hints: {
      1: "The deboning is complete, but there is one final hygiene step required before the fish can be packed.",
      2: "Select the water tool and hold your cursor over the fish to rinse away any remaining bone fragments or debris.",
    },
  },
  {
    id: 11,
    key: 'inspection',
    title: 'Quality Inspection',
    shortTitle: 'Inspect',
    icon: '🔎',
    description: 'Inspect the deboned fish carefully to confirm all bones have been removed. This self-check reinforces procedural completeness.',
    instruction: 'Examine all highlighted zones on the fish. Click each zone to inspect it.',
    completionMessage: 'Inspection complete — bangus fully deboned!',
    tool: null,
    requiresHold: false,
    scoreWeight: 8,
    hints: {
      1: "Before finishing, you must verify the quality of your work by examining specific areas of the fish.",
      2: "Click each highlighted inspection zone on the fish one by one. Every zone must be checked to complete the quality inspection.",
    },
  },
]

export const TOTAL_STEPS = STEP_DEFINITIONS.length          // 11
export const TOTAL_SCORE = STEP_DEFINITIONS.reduce((sum, s) => sum + s.scoreWeight, 0) // 100
